// This class handles the devices connecting to the internal MQTT broker. This includes both device provisioning
// and minimal wrappers for actual data exchange. The device class is responsible for generating/parsing the payload.

import { generateDeployResponse } from './provisioning'
import { TypedEmitter } from 'tiny-typed-emitter'
import { Client, PublishPacket, type Broker } from '../mqtt-broker'
import { ClipDeployMessage, ClipEnvelope, ClipMessage } from './clip'

import log from '@/util/logging'
import { Metadata } from '../thinq'

type DeviceEvents = {
    data: (packet: Buffer) => void
    // Kept in the shared device event surface; ThinQ 2 currently does not emit ThinQ 1 response envelopes.
    response: (body: Record<string, unknown>) => void
    sendData: (buf: Buffer) => void
    close: () => void
}

export class Device extends TypedEmitter<DeviceEvents> {
    // this could be a stream but why bother...
    readonly platform = 'thinq2'

    // The device's real provisioning info, verbatim from its deploy message. The bridge
    // forwards these upstream so the real LG cloud sees the device's true firmware/protocol
    // version (esp. appInfo.protocolVer) instead of hardcoded placeholders — reporting the
    // wrong protocolVer makes the cloud pick a wire encoding the firmware ignores (e.g. the
    // reservation "service" poll came framed byte5=0xFD and the device never answered it).
    deployAppInfo?: Record<string, unknown>
    deployPlatformInfo?: Record<string, unknown>

    /*
     * Called with a message from the appliance that this class has no handler for, so the bridge
     * can put it in front of the real cloud and carry the answer back. A plain callback rather than
     * an event, because the two device platforms share one union type and giving only this one an
     * extra event makes every listener on that union uncallable.
     */
    onUnhandledClip?: (payload: ClipMessage) => void

    constructor(
        readonly broker: Broker,
        readonly topic: string,
        readonly id: string,
        readonly meta: Metadata,
    ) {
        super()
    }

    send(cmd: string, type: number, data: string | object) {
        this.publish(JSON.stringify({ did: this.id, mid: Date.now(), cmd: cmd, type: type, data: data }))
    }

    /*
     * Hands the appliance a message from the cloud exactly as the cloud wrote it.
     *
     * Rebuilding it - which is what send() above does, stamping a mid of its own - defeats the one
     * thing an acknowledgement is for. The appliance matches an ack to its own pending message by mid,
     * so an ack carrying a mid it never sent is worth no more than no ack at all: it repeats the
     * report, and the cloud counts the repeat. The ceiling cassettes here were caught doing exactly
     * that, resending an identical frame up to fifteen times on a four-second ladder.
     *
     * The same argument runs the other way for a downlink packet. If the appliance answers one, the
     * answer echoes the mid it was given, and a mid this side invented is one the cloud cannot match.
     * So nothing is rewritten in either case - the bridge is a proxy, and this is what proxying means.
     */
    forward_clip(payload: ClipEnvelope) {
        // Reported to the monitor on the way past, so a relayed packet is still captured there.
        if (payload.cmd === 'packet' && typeof payload.data === 'string')
            this.emit('sendData', Buffer.from(payload.data, 'hex'))

        this.publish(JSON.stringify(payload))
    }

    private publish(messagestr: string) {
        this.broker.publish(
            { topic: this.topic, retain: false, qos: 0, dup: false, payload: messagestr },
            null /* message generated by the broker itself */,
        )
    }

    send_packet(buf: Buffer) {
        this.emit('sendData', buf)
        this.send('packet', 1, buf.toString('hex'))
    }
}

function trimNull(buf: Buffer) {
    if (!buf || !buf.length || buf[buf.length - 1]) return buf
    return buf.subarray(0, buf.length - 1)
}

type ClientWithExtra = Client & {
    deviceObj: undefined | Device
    deployMsg: undefined | ClipDeployMessage
}

type DeviceAcceptorEvents = {
    newDevice: (dev: Device) => void
    dropDevice: (id: string) => void
}

export class DeviceAcceptor extends TypedEmitter<DeviceAcceptorEvents> {
    clientsById: Record<string, Client> = {}
    constructor(readonly broker: Broker) {
        super()

        broker.on('publish', (packet, client) => {
            if (client) {
                log('incoming', packet.topic, packet.payload.toString('utf-8'), 'retain:', packet.retain)
            } else {
                log('outgoing', packet.topic, packet.payload.toString('utf-8'), 'retain:', packet.retain)
                return // don't process outgoing packets further
            }

            try {
                if (packet.topic.indexOf('clip/') >= 0) {
                    const payload = JSON.parse(trimNull(Buffer.from(packet.payload)).toString('utf-8'))
                    this.mqtt(packet.topic, payload, client as ClientWithExtra)
                }
            } catch (err) {
                console.warn(err, packet.payload.toString('hex'))
            }
        })

        broker.on('disconnect', this.disconnected.bind(this))
    }

    mqtt(topic: string, payload: ClipMessage, client: ClientWithExtra) {
        // experiment: try to support devices which use other topic formats
        topic = topic.replace(/^.*\/clip/, 'clip')

        if (topic === 'clip/message/devices/' + payload.did) {
            if (payload.cmd === 'completeProvisioning_ack') {
                this.completeProvisioning(payload.did, payload, client)
            }

            if (payload.cmd === 'device_packet' && payload.did === client.deployMsg?.did) {
                if (client.deviceObj) {
                    const buf = Buffer.from(payload.data as string, 'hex')
                    client.deviceObj.emit('data', buf)
                }
            }

            if (payload.cmd === 'req_timesync' && client.deployMsg && payload.did === client.deployMsg.did) {
                this.timeSyncRequest(client)
            }

            // The appliance's side of the same gap - anything it publishes that is not one of
            // the three cmds above used to be dropped here, so its answer to a liveness check, or a
            // firmware request from it, was never seen. Hand it to whoever is listening.
            // This is what makes firmware updates possible: the exchange the cloud starts with
            // reqUniversalCtrl is answered by respUniversalCtrl, and neither is handled above.
            if (!['completeProvisioning_ack', 'device_packet', 'req_timesync'].includes(payload.cmd)) {
                log('incoming', `unhandled cmd ${payload.cmd} on ${topic}`)
                if (client.deviceObj && payload.did === client.deviceObj.id) client.deviceObj.onUnhandledClip?.(payload)
            }
        }

        if (topic === 'clip/provisioning/devices/' + payload.did) {
            // Same blind spot as above, on the other topic. Log only - the upstream
            // side would have to publish an answer to the provisioning topic rather than the
            // message one, so relaying is left until something actually turns up here.
            if (payload.cmd !== 'preDeploy' && payload.cmd !== 'deploy')
                log('incoming', `unhandled cmd ${payload.cmd} on ${topic}`)

            if (payload.cmd === 'preDeploy' || payload.cmd === 'deploy') {
                client.deployMsg = payload as ClipDeployMessage
                this.broker.publish(
                    {
                        topic: 'lime/devices/' + payload.did,
                        retain: false,
                        qos: 0,
                        dup: false,
                        payload: JSON.stringify(generateDeployResponse(payload as ClipDeployMessage)),
                    },
                    null,
                )
            }
        }
    }

    completeProvisioning(deviceId: string, payload: ClipMessage, client: ClientWithExtra) {
        if (!client.deployMsg) {
            console.warn('completeProvisioning_ack received without deploy/preDeploy')
            return
        }

        if (client.deviceObj) {
            console.warn('completeProvisioning_ack received twice?')
            return
        }

        if (this.clientsById[deviceId]) {
            console.warn(`device ${deviceId} already connected, dropping the old one`)
            this.clientsById[deviceId].destroy()
        }

        this.clientsById[deviceId] = client

        const meta: Metadata = {
            modelId: client.deployMsg.kind,
            modelName: client.deployMsg.data?.appInfo?.modelName,
            swVersion: client.deployMsg.data?.appInfo?.softVer,
            deviceType: client.deployMsg.data?.appInfo?.DeviceType,
        }

        const dev = new Device(this.broker, 'lime/devices/' + deviceId, deviceId, meta)
        dev.deployAppInfo = client.deployMsg.data?.appInfo as Record<string, unknown> | undefined
        dev.deployPlatformInfo = client.deployMsg.data?.platformInfo as Record<string, unknown> | undefined
        client.deviceObj = dev
        this.emit('newDevice', dev)
    }

    timeSyncRequest(client: ClientWithExtra) {
        const now = new Date()
        const buf = Buffer.alloc(7)
        buf[0] = now.getUTCFullYear() % 100
        buf[1] = now.getUTCMonth()
        buf[2] = now.getUTCDate()
        buf[3] = now.getUTCHours()
        buf[4] = now.getUTCMinutes()
        buf[5] = now.getUTCSeconds()
        buf[6] = now.getUTCDay()

        const deviceId = client.deployMsg?.did
        if (!deviceId) return

        this.broker.publish(
            {
                topic: 'lime/devices/' + deviceId,
                retain: false,
                qos: 0,
                dup: false,
                payload: JSON.stringify({
                    did: deviceId,
                    mid: Date.now(),
                    cmd: 'resp_timesync',
                    type: 1,
                    data: buf.toString('base64'),
                }),
            },
            null,
        )
    }

    disconnected(_client: Client) {
        let client = _client as ClientWithExtra
        if (client.deviceObj) {
            delete this.clientsById[client.deviceObj.id]
            this.emit('dropDevice', client.deviceObj.id)
            client.deviceObj.emit('close')
            client.deviceObj = undefined
        }
    }
}
